FROM centos:7

ARG CC=gcc

RUN yum install -y \
	findutils \
	gcc \
	git \
	gnutls-devel \
	iproute \
	iptables \
	libaio-devel \
	libasan \
	libcap-devel \
	libnet-devel \
	libnl3-devel \
	make \
	procps-ng \
	protobuf-c-devel \
	protobuf-devel \
	protobuf-python \
	python \
	python-flake8 \
	python-ipaddress \
	python2-future \
	python2-junit_xml \
	python-yaml \
	python-six \
	sudo \
	tar \
	which \
	e2fsprogs \
	python2-pip \
	rubygem-asciidoctor \
	rpm-build  && \
	mkdir -p /root/rpmbuild/SPECS && \
	mkdir -p /root/rpmbuild/SOURCES


