FROM mirrors.tencent.com/tlinux/tlinux3.2_mini_gcc_9.3.0:v20210914
#FROM centos:8

ARG CC=gcc

RUN yum install -y \
	findutils \
	gcc \
	git \
	gnutls-devel \
	iproute \
	iptables \
	libaio-devel \
	libasan \
	libcap-devel \
	libnet-devel \
	libnl3-devel \
	libselinux-devel \
	make \
	procps-ng \
	protobuf-c-devel \
	protobuf-devel \
	protobuf-python3 \
	python3 \
	python3-netaddr \
	python3-devel \
	sudo \
	tar \
	which \
	e2fsprogs \
	python3-pip \
	rpm-build  && \
	mkdir -p /root/rpmbuild/SPECS && \
	mkdir -p /root/rpmbuild/SOURCES


